apiVersion: apps/v1
kind: Deployment
metadata:
  name: my-bank-front-app
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: my-bank-front-app
  template:
    metadata:
      labels:
        app: my-bank-front-app
    spec:
      serviceAccountName: default
      containers:
        - name: my-bank-front-app
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - name: http
              containerPort: {{ .Values.service.port }}
              protocol: TCP
          env:
            - name: SERVER_PORT
              value: {{ .Values.env.server_port | quote }}
            - name: FRONTEND_CLIENT_SECRET
              valueFrom:
                secretKeyRef:
                  name: bank-secrets
                  key: frontend-client-secret
            - name: GATEWAY_URL
              value: {{ .Values.env.gateway_url | quote }}
            - name: KEYCLOAK_INTERNAL_URL
              value: {{ .Values.env.keycloak_internal_url | quote }}
            - name: KEYCLOAK_FRONTEND_URL
              value: {{ .Values.env.keycloak_frontend_url | quote }}
            - name: OAUTH2_REDIRECT_URI
              value: "http://bank.local/login/oauth2/code/keycloak"
          {{- with .Values.livenessProbe }}
          livenessProbe:
            {{- toYaml . | nindent 12 }}
          {{- end }}
          {{- with .Values.readinessProbe }}
          readinessProbe:
            {{- toYaml . | nindent 12 }}
          {{- end }}