apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "grafana.fullname" . }}
  labels:
    {{- include "grafana.labels" . | nindent 4 }}
data:
  grafana.ini: |
    [server]
    http_port = 3000
    
    [security]
    admin_user = {{ .Values.grafana.adminUser }}
    admin_password = {{ .Values.grafana.adminPassword }}
    secret_key = {{ .Values.grafana.security.secretKey }}
    
    [database]
    type = sqlite3
    path = /var/lib/grafana/grafana.db
    
    [log]
    mode = console
    level = info
    
    [users]
    allow_sign_up = false
    
    [auth.anonymous]
    enabled = false
