apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "logstash.fullname" . }}
  labels:
    {{- include "logstash.labels" . | nindent 4 }}
spec:
  {{- if not .Values.autoscaling.enabled }}
  replicas: {{ .Values.replicaCount }}
  {{- end }}
  selector:
    matchLabels:
      {{- include "logstash.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      annotations:
        checksum/config: {{ include (print $.Template.BasePath "/configmap.yaml") . | sha256sum }}
        {{- with .Values.podAnnotations }}
        {{- toYaml . | nindent 8 }}
        {{- end }}
      labels:
        {{- include "logstash.selectorLabels" . | nindent 8 }}
    spec:
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      serviceAccountName: {{ include "logstash.serviceAccountName" . }}
      securityContext:
        {{- toYaml .Values.podSecurityContext | nindent 8 }}
      containers:
        - name: {{ .Chart.Name }}
          securityContext:
            {{- toYaml .Values.securityContext | nindent 12 }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - name: beats
              containerPort: {{ .Values.logstash.input.beats.port }}
              protocol: TCP
            - name: http
              containerPort: 9600
              protocol: TCP
          livenessProbe:
            httpGet:
              path: /
              port: http
            initialDelaySeconds: 180
            timeoutSeconds: 5
            periodSeconds: 10
            failureThreshold: 6
          readinessProbe:
            httpGet:
              path: /
              port: http
            initialDelaySeconds: 60
            timeoutSeconds: 5
            periodSeconds: 5
            failureThreshold: 12
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
          env:
            - name: LS_JAVA_OPTS
              value: "-Xms{{ .Values.logstash.jvm.xms }} -Xmx{{ .Values.logstash.jvm.xmx }}"
            - name: pipeline.workers
              value: "{{ .Values.logstash.pipeline.workers }}"
            - name: pipeline.batch.size
              value: "{{ .Values.logstash.pipeline.batch_size }}"
            - name: pipeline.batch.delay
              value: "{{ .Values.logstash.pipeline.batch_delay }}"
            - name: KAFKA_BOOTSTRAP_SERVERS
              value: {{ .Values.global.kafkaConfig.bootstrapServers | quote }}
            - name: KAFKA_LOGS_TOPIC
              value: {{ .Values.global.kafkaConfig.logsTopic | quote }}
            - name: KAFKA_LOGS_GROUP
              value: {{ .Values.global.kafkaConfig.logsGroup | quote }}
          volumeMounts:
            - name: config
              mountPath: /usr/share/logstash/pipeline/logstash.conf
              subPath: logstash.conf
            - name: storage
              mountPath: /usr/share/logstash/data
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      volumes:
        - name: config
          configMap:
            name: {{ include "logstash.fullname" . }}
        - name: storage
          {{- if .Values.logstash.storage.enabled }}
          persistentVolumeClaim:
            claimName: {{ include "logstash.fullname" . }}
          {{- else }}
          emptyDir: {}
          {{- end }}
