apiVersion: apps/v1
kind: Deployment
metadata:
  name: cash-service
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: cash-service
  template:
    metadata:
      labels:
        app: cash-service
    spec:
      containers:
        - name: cash-service
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - name: http
              containerPort: {{ .Values.service.port }}
              protocol: TCP
          env:
            - name: SPRING_DATASOURCE_URL
              value: {{ .Values.env.spring_datasource_url | quote }}
            - name: SPRING_DATASOURCE_USERNAME
              value: "postgres"
            - name: SPRING_DATASOURCE_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: bank-secrets
                  key: db-password
            - name: SPRING_CLOUD_CONSUL_ENABLED
              value: "false"
            - name: CASH_CLIENT_SECRET
              valueFrom:
                secretKeyRef:
                  name: bank-secrets
                  key: cash-client-secret
          {{- with .Values.livenessProbe }}
          livenessProbe:
            {{- toYaml . | nindent 12 }}
          {{- end }}
          {{- with .Values.readinessProbe }}
          readinessProbe:
            {{- toYaml . | nindent 12 }}
          {{- end }}