apiVersion: apps/v1
kind: Deployment
metadata:
  name: cash-service
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: cash-service
  template:
    metadata:
      labels:
        app: cash-service
    spec:
      containers:
        - name: cash-service
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - name: http
              containerPort: {{ .Values.service.port }}
              protocol: TCP
          env:
            - name: ACCOUNTS_SERVICE_URL
              value: "http://accounts-service:8081"
            - name: NOTIFICATIONS_SERVICE_URL
              value: "http://notifications-service:8082"
            - name: SPRING_CLOUD_CONSUL_ENABLED
              value: "false"
            - name: CASH_CLIENT_SECRET
              valueFrom:
                secretKeyRef:
                  name: bank-secrets
                  key: cash-client-secret
            - name: KEYCLOAK_JWK_SET_URI
              value: "http://keycloak:8080/realms/bank-app-realm/protocol/openid-connect/certs"
            - name: KEYCLOAK_TOKEN_URI
              value: "http://keycloak:8080/realms/bank-app-realm/protocol/openid-connect/token"
          {{- with .Values.livenessProbe }}
          livenessProbe:
            {{- toYaml . | nindent 12 }}
          {{- end }}
          {{- with .Values.readinessProbe }}
          readinessProbe:
            {{- toYaml . | nindent 12 }}
          {{- end }}