services:
  # --- Инфраструктура ---
  consul:
    image: hashicorp/consul:1.15.4
    container_name: consul
    ports:
      - "8500:8500" # UI и API (для твоих сервисов)
    command: "agent -dev -client=0.0.0.0"
    networks:
      - microservices-network

  common-db:
    image: postgres:16
    container_name: common-db
    environment:
      POSTGRES_DB: ${COMMON_DB_NAME}
      POSTGRES_USER: ${COMMON_DB_USERNAME}
      POSTGRES_PASSWORD: ${COMMON_DB_PASSWORD}
    ports:
      - "5433:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${COMMON_DB_USERNAME} -d ${COMMON_DB_NAME}"]
      interval: 5s
      timeout: 5s
      retries: 5
    networks:
      - microservices-network

  keycloak:
    image: quay.io/keycloak/keycloak:24.0.0
    command: start-dev
    environment:
      KC_BOOTSTRAP_ADMIN_USERNAME: admin
      KC_BOOTSTRAP_ADMIN_PASSWORD: admin
    ports:
      - "8080:8080"
    networks:
      - microservices-network

  # --- Микросервисы ---
  gateway-service:
    build: ./gateway-service
    ports:
      - "8000:8080"
    environment:
      - SPRING_CLOUD_CONSUL_HOST=consul
      - SPRING_CLOUD_CONSUL_DISCOVERY_HOSTNAME=gateway-service
      - SPRING_CLOUD_CONSUL_DISCOVERY_PREFER-IP-ADDRESS=false
      - SPRING_SECURITY_OAUTH2_RESOURCESERVER_JWT_ISSUER_URI=http://keycloak:8080/realms/bank-app-realm
    depends_on:
      - keycloak
      - consul
    networks:
      - microservices-network

  accounts-service:
    build: ./accounts-service
    ports:
      - "8081:8081"
    environment:
      - SPRING_CLOUD_CONSUL_HOST=consul
      - SPRING_DATASOURCE_URL=jdbc:postgresql://common-db:5432/${COMMON_DB_NAME}
      - SPRING_DATASOURCE_USERNAME=${COMMON_DB_USERNAME}
      - SPRING_DATASOURCE_PASSWORD=${COMMON_DB_PASSWORD}
      - SPRING_SECURITY_OAUTH2_RESOURCESERVER_JWT_ISSUER_URI=http://keycloak:8080/realms/bank-app-realm
      - OAUTH2_ISSUER_URI=http://keycloak:8080/realms/bank-app-realm
      - SERVER_PORT=8081
      - CLIENT_SECRET=${CLIENT_SECRET}
    depends_on:
      common-db:
        condition: service_healthy
      keycloak:
        condition: service_started
      consul:
        condition: service_started
    networks:
      - microservices-network

  notifications-service:
    build: ./notifications-service
    ports:
      - "8082:8082"
    environment:
      - SPRING_CLOUD_CONSUL_HOST=consul
      - SPRING_DATASOURCE_URL=jdbc:postgresql://common-db:5432/${COMMON_DB_NAME}
      - SPRING_DATASOURCE_USERNAME=${COMMON_DB_USERNAME}
      - SPRING_DATASOURCE_PASSWORD=${COMMON_DB_PASSWORD}
      - SPRING_SECURITY_OAUTH2_RESOURCESERVER_JWT_ISSUER_URI=http://keycloak:8080/realms/bank-app-realm
      - OAUTH2_ISSUER_URI=http://keycloak:8080/realms/bank-app-realm
      - SERVER_PORT=8082
    depends_on:
      common-db:
        condition: service_healthy
      keycloak:
        condition: service_started
      consul:
        condition: service_started
    networks:
      - microservices-network

  transfer-service:
    build: ./transfer-service
    environment:
      - SPRING_CLOUD_CONSUL_HOST=consul
      - OAUTH2_ISSUER_URI=http://keycloak:8080/realms/bank-app-realm
      - ACCOUNTS_SERVICE_URL=http://accounts-service:8081
      - NOTIFICATIONS_SERVICE_URL=http://notifications-service:8082
      - TRANSFER_CLIENT_SECRET=${TRANSFER_CLIENT_SECRET}
    depends_on:
      - accounts-service
      - consul
    networks:
      - microservices-network

  cash-service:
    build: ./cash-service
    environment:
      - SPRING_CLOUD_CONSUL_HOST=consul
      - OAUTH2_ISSUER_URI=http://keycloak:8080/realms/bank-app-realm
      - ACCOUNTS_SERVICE_URL=http://accounts-service:8081
      - NOTIFICATIONS_SERVICE_URL=http://notifications-service:8082
      - CASH_CLIENT_SECRET=${CASH_CLIENT_SECRET}
    depends_on:
      - accounts-service
      - consul
    networks:
      - microservices-network

networks:
  microservices-network:
    driver: bridge