global:
  kafkaConfig:
    bootstrapServers: "my-bank-app-kafka:9092"
    logsTopic: "application.logs"
    logsGroup: "logstash-logs-consumer"
  zipkinConfig:
    endpoint: "http://my-bank-app-zipkin:9411/api/v2/spans"
  environment: "kubernetes"

replicaCount: 1

image:
  repository: my-bank-app-gateway-service
  pullPolicy: IfNotPresent
  tag: "latest"

service:
  port: 8080

env:
  server_port: "8080"
  accounts_url: "http://accounts-service:8081"
  transfer_url: "http://transfer-service:8085"
  cash_url: "http://cash-service:8084"


livenessProbe:
  httpGet:
    path: /actuator/health/liveness
    port: http
  initialDelaySeconds: 80
  periodSeconds: 10
  timeoutSeconds: 5
  failureThreshold: 5

readinessProbe:
  httpGet:
    path: /actuator/health/readiness
    port: http
  initialDelaySeconds: 70
  periodSeconds: 5
  timeoutSeconds: 3
  failureThreshold: 5