replicaCount: 1

image:
  repository: my-bank-app-accounts-service
  pullPolicy: IfNotPresent
  tag: "latest"

service:
  type: ClusterIP
  port: 8081

env:
  spring_datasource_url: "jdbc:postgresql://common-db:5432/bank_db"
  server_port: "8081"
  keycloak_url: "http://keycloak:8080/realms/bank-app-realm"

livenessProbe:
  httpGet:
    path: /actuator/health/liveness
    port: 8081
  initialDelaySeconds: 20
  periodSeconds: 10

readinessProbe:
  httpGet:
    path: /actuator/health/readiness
    port: 8081
  initialDelaySeconds: 20
  periodSeconds: 5

resources:
  limits:
    memory: "512Mi"
    cpu: "500m"
  requests:
    memory: "256Mi"
    cpu: "100m"