server:
  port: 8080 #  фронтенд

spring:
  application:
    name: gateway-service
  cloud:
    consul:
      host: ${SPRING_CLOUD_CONSUL_HOST:localhost}
      port: 8500               # Порт Consul (8500 по умолчанию)
      discovery:
        service-name: gateway-service
      config:
        enabled: true            # Включаем Consul Config для внешней конфигурации
        prefix: config           # Префикс в KV-хранилище Consul (по умолчанию "config")
        defaultContext: application  # Контекст по умолчанию
    gateway:
      default-filters:
        - TokenRelay
      routes:
        # Accounts
        - id: accounts-route
          uri: lb://accounts-service
          predicates:
            - Path=/api/accounts/**

        # Notifications
        - id: notifications-route
          uri: lb://notifications-service
          predicates:
            - Path=/api/notifications/**

        # Transfer
        - id: transfer-route
          uri: lb://transfer-service
          predicates:
            - Path=/transfer/**

        # Cash
        - id: cash-route
          uri: lb://cash-service
          predicates:
            - Path=/cash/**

  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: http://keycloak:8080/realms/my-bank-app
      client:
        provider:
          keycloak:
            issuer-uri: http://keycloak:8080/realms/my-bank-app