server:
  port: 8080 #  фронтенд

spring:
  application:
    name: gateway-service
  cloud:
    consul:
      host: ${SPRING_CLOUD_CONSUL_HOST:localhost}
      port: 8500
      discovery:
        service-name: gateway-service
        enabled: true
        register: true
        health-check-path: /actuator/health
        health-check-interval: 10s
        prefer-ip-address: false
        instance-id: ${spring.application.name}:${random.value}
        hostname: ${spring.application.name}
      config:
        enabled: true            # Включаем Consul Config для внешней конфигурации
        prefix: config           # Префикс в KV-хранилище Consul (по умолчанию "config")
        defaultContext: application  # Контекст по умолчанию

  config:
    import: "optional:consul:${spring.cloud.consul.host}:${spring.cloud.consul.port}"
    gateway:
      default-filters:
        - TokenRelay
      routes:
        # Accounts
        - id: accounts-route
          uri: lb://accounts-service
          predicates:
            - Path=/api/accounts/**

        # Notifications
        - id: notifications-route
          uri: lb://notifications-service
          predicates:
            - Path=/api/notifications/**

        # Transfer
        - id: transfer-route
          uri: lb://transfer-service
          predicates:
            - Path=/transfer/**

        # Cash
        - id: cash-route
          uri: lb://cash-service
          predicates:
            - Path=/cash/**

  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: http://keycloak:8080/realms/my-bank-app
      client:
        provider:
          keycloak:
            issuer-uri: http://keycloak:8080/realms/my-bank-app