services:
  cash-service:
    build: .
    ports:
      - "${SERVER_PORT}:${SERVER_PORT}"
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://${cash_DB_HOST}:5432/${cash_DB_NAME}
      SPRING_DATASOURCE_USERNAME: ${cash_DB_USERNAME}
      SPRING_DATASOURCE_PASSWORD: ${cash_DB_PASSWORD}
      SERVER_PORT: ${SERVER_PORT}
    depends_on:
      - cash-db

  cash-db:
    image: postgres:16
    container_name: cash-db
    environment:
      POSTGRES_DB: ${cash_DB_NAME}
      POSTGRES_USER: ${cash_DB_USERNAME}
      POSTGRES_PASSWORD: ${cash_DB_PASSWORD}
    ports:
      - "5433:5432"
