apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "elasticsearch.fullname" . }}
  labels:
    {{- include "elasticsearch.labels" . | nindent 4 }}
data:
  elasticsearch.yml: |
    cluster.name: {{ .Values.elasticsearch.cluster.name }}
    discovery.type: {{ .Values.elasticsearch.discovery.type }}
    network.host: {{ .Values.elasticsearch.network.host }}
    xpack.security.enabled: {{ .Values.elasticsearch.security.enabled }}
