services:
  transfer-service:
    build: .
    ports:
      - "${SERVER_PORT}:${SERVER_PORT}"
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://${transfer_DB_HOST}:5432/${transfer_DB_NAME}
      SPRING_DATASOURCE_USERNAME: ${transfer_DB_USERNAME}
      SPRING_DATASOURCE_PASSWORD: ${transfer_DB_PASSWORD}
      SERVER_PORT: ${SERVER_PORT}
    depends_on:
      - transfer-db

  transfer-db:
    image: postgres:16
    container_name: transfer-db
    environment:
      POSTGRES_DB: ${transfer_DB_NAME}
      POSTGRES_USER: ${transfer_DB_USERNAME}
      POSTGRES_PASSWORD: ${transfer_DB_PASSWORD}
    ports:
      - "5433:5432"
