global:
  kafkaConfig:
    bootstrapServers: "my-bank-app-kafka:9092"
    logsTopic: "application.logs"
  zipkinConfig:
    endpoint: "http://my-bank-app-zipkin:9411/api/v2/spans"
  environment: "kubernetes"

replicaCount: 1

image:
  repository: my-bank-app-transfer-service
  pullPolicy: IfNotPresent
  tag: "latest"

service:
  port: 8085

env:
  server_port: "8085"

livenessProbe:
  httpGet:
    path: /actuator/health/liveness
    port: 8085
  initialDelaySeconds: 90
  periodSeconds: 10
  timeoutSeconds: 5
  failureThreshold: 5

readinessProbe:
  httpGet:
    path: /actuator/health/readiness
    port: 8085
  initialDelaySeconds: 75
  periodSeconds: 5
  timeoutSeconds: 3
  failureThreshold: 5