replicaCount: 1

image:
  repository: my-bank-app-my-bank-front-app
  pullPolicy: IfNotPresent
  tag: "latest"

service:
  port: 8083

env:
  server_port: "8083"
  gateway_url: "http://gateway-service:8000"
  keycloak_internal_url: "http://keycloak:8080/auth"
  keycloak_frontend_url: "http://bank.local/auth"
