apiVersion: v1
kind: Secret
metadata:
  name: bank-secrets
type: Opaque
stringData:
  db-password: "password"
  client-secret: "CEkyZ80iFS1zZCh6tITuWYdMblZfttg4"
  cash-client-secret: "nyiCZsLgraBpH8ht4e5WeiGgYmrdDVeF"
  transfer-client-secret: "BILxNPZ4Uz69zOspfLLKkUft4tQ9LqkQ"