spring:
  application:
    name: accounts-application
  datasource:
    url: ${SPRING_DATASOURCE_URL}
    username: ${SPRING_DATASOURCE_USERNAME}
    password: ${SPRING_DATASOURCE_PASSWORD}
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: http://localhost:8080/realms/bank-app-realm
      client:
        registration:
          notifications-client:
            provider: keycloak
            client-id: accounts-service-client
            client-secret: ${CLIENT_SECRET}
            authorization-grant-type: client_credentials
            scope: openid, profile
        provider:
          keycloak:
            issuer-uri: http://localhost:8080/realms/bank-app-realm

server:
  port: ${SERVER_PORT:8081}

management:
  endpoints:
    web:
      exposure:
        include: health, info
  endpoint:
    health:
      show-details: always
