spring:
  application:
    name: my-bank-front-app
  config:
    import: optional:consul:localhost:8500
  cloud:
    consul:
      host: localhost          # ????? Consul (?? ????????? localhost)
      port: 8500               # ???? Consul (8500 ?? ?????????)
      discovery:
        service-name: my-bank-front-app
      config:
        enabled: true            # ???????? Consul Config ??? ??????? ????????????
        prefix: config           # ??????? ? KV-????????? Consul (?? ????????? "config")
        defaultContext: application  # ???????? ?? ?????????