apiVersion: apps/v1
kind: Deployment
metadata:
  name: transfer-service
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: transfer-service
  template:
    metadata:
      labels:
        app: transfer-service
    spec:
      containers:
        - name: transfer-service
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - name: http
              containerPort: {{ .Values.service.port }}
              protocol: TCP
          env:
            - name: SERVER_PORT
              value: {{ .Values.env.server_port | quote }}
            - name: TRANSFER_CLIENT_SECRET
              valueFrom:
                secretKeyRef:
                  name: bank-secrets
                  key: transfer-client-secret
            - name: SPRING_CLOUD_CONSUL_ENABLED
              value: "false"
            - name: KEYCLOAK_JWK_SET_URI
              value: "http://keycloak:8080/realms/bank-app-realm/protocol/openid-connect/certs"
            - name: KEYCLOAK_TOKEN_URI
              value: "http://keycloak:8080/realms/bank-app-realm/protocol/openid-connect/token"
          {{- with .Values.livenessProbe }}
          livenessProbe:
            {{- toYaml . | nindent 12 }}
          {{- end }}
          {{- with .Values.readinessProbe }}
          readinessProbe:
            {{- toYaml . | nindent 12 }}
          {{- end }}