apiVersion: apps/v1
kind: Deployment
metadata:
  name: accounts-service
spec:
  replicas: {{ .Values.replicaCount | default 1 }}
  selector:
    matchLabels:
      app: accounts-service
  template:
    metadata:
      labels:
        app: accounts-service
    spec:
      initContainers:
        - name: wait-for-db
          image: busybox:1.36
          command:
            - sh
            - -c
            - "until nc -zvw 2 common-db 5432; do echo 'Waiting for database connection...'; sleep 2; done; echo 'DB is up!';"
      containers:
        - name: accounts-service
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag | default "latest" }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - name: http
              containerPort: {{ .Values.service.port }}
              protocol: TCP
          env:
            - name: SPRING_DATASOURCE_URL
              value: {{ .Values.env.spring_datasource_url | quote }}
            - name: SPRING_DATASOURCE_USERNAME
              value: "postgres"
            - name: SPRING_DATASOURCE_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: bank-secrets
                  key: db-password
            - name: SPRING_CLOUD_CONSUL_ENABLED
              value: "false"
            - name: CLIENT_SECRET
              valueFrom:
                secretKeyRef:
                  name: bank-secrets
                  key: client-secret
            - name: KEYCLOAK_JWK_SET_URI
              value: "http://keycloak:8080/realms/bank-app-realm/protocol/openid-connect/certs"
            - name: KEYCLOAK_TOKEN_URI
              value: "http://keycloak:8080/realms/bank-app-realm/protocol/openid-connect/token"
            - name: KAFKA_BOOTSTRAP_SERVERS
              value: {{ .Values.global.kafkaConfig.bootstrapServers | quote }}
            - name: KAFKA_NOTIFICATIONS_TOPIC
              value: {{ .Values.global.kafkaConfig.notificationsTopic | quote }}
          {{- with .Values.livenessProbe }}
          livenessProbe:
            {{- toYaml . | nindent 12 }}
          {{- end }}
          {{- with .Values.readinessProbe }}
          readinessProbe:
            {{- toYaml . | nindent 12 }}
          {{- end }}