replicaCount: 1

image:
  repository: quay.io/keycloak/keycloak
  tag: "24.0.0"
  pullPolicy: IfNotPresent

service:
  type: ClusterIP
  port: 80

env:
  KC_HOSTNAME_STRICT: "false"
  KC_HOSTNAME_STRICT_HTTPS: "false"
  KC_HTTP_ENABLED: "true"
  KEYCLOAK_ADMIN: "admin"
  KEYCLOAK_ADMIN_PASSWORD: "admin"

ingress:
  enabled: true
  className: "nginx"
  hosts:
    - host: keycloak.bank.local
      paths:
        - path: /
          pathType: ImplementationSpecific

livenessProbe:
  httpGet:
    path: /health/live
    port: 8080
  initialDelaySeconds: 90
readinessProbe:
  httpGet:
    path: /health/ready
    port: 8080
  initialDelaySeconds: 90

volumes:
  - name: realm-import
    configMap:
      name: keycloak-realm-config
volumeMounts:
  - name: realm-import
    mountPath: /opt/keycloak/data/import